export const data = [
	{
		id: 3,
		name: 'Огурец Малика',
		price: 249,
		weight: 1000,
		category: 'Овощи',
		group: 'Огурцы',
		imgUrl: 'webp125/огурец малика_125.webp',
		bigImgUrl: 'awif245/огурец малика_245.awif',
	},
	{
		id: 4,
		name: 'Огурец сладкий',
		price: 149,
		weight: 1000,
		category: 'Овощи',
		group: 'Огурцы',
		imgUrl: 'webp125/огурец сладкий_125.webp',
		bigImgUrl: 'awif245/огурец сладкий_245.awif',
	},
	{
		id: 5,
		name: 'Огурец Зозуля',
		price: 99,
		weight: 1000,
		category: 'Овощи',
		group: 'Огурцы',
		imgUrl: 'webp125/огурец зозуля_125.webp',
		bigImgUrl: 'awif245/огурец зозуля_245.awif',
	},
	{
		id: 6,
		name: 'Соленья Рязани',
		price: 29,
		weight: 1000,
		category: 'Овощи',
		group: 'Огурцы',
		imgUrl: 'webp125/огурец малика_125.webp',
		bigImgUrl: 'awif245/огурец малика_245.awif',
	},
	{
		id: 7,
		name: 'Томаты',
		price: 79,
		weight: 1000,
		category: 'Овощи',
		group: 'Томаты',
		imgUrl: 'webp125/томаты_125.webp',
		bigImgUrl: 'awif245/томаты_245.awif',
	},
	{
		id: 11,
		name: 'Розовые помидоры',
		price: 69,
		weight: 1000,
		category: 'Овощи',
		group: 'Томаты',
		imgUrl: 'webp125/помидоры розовые_125.webp',
		bigImgUrl: 'awif245/помидоры розовые_245.awif',
	},
	{
		id: 12,
		name: 'Сыр Сметанковый',
		price: 679,
		weight: 100,
		category: 'Молочные продукты',
		group: 'Сыры',
		imgUrl: 'webp125/сыр сметанковый_125.webp',
		bigImgUrl: 'awif245/сыр сметанковый_245.awif',
	},
	{
		id: 13,
		name: 'Сыр Зигеркейз',
		price: 559,
		weight: 100,
		category: 'Молочные продукты',
		group: 'Сыры',
		imgUrl: 'webp125/сыр зигеркейз_125.webp',
		bigImgUrl: 'awif245/сыр зигеркейз_245.awif',
	},
	{
		id: 14,
		name: 'Российский сыр',
		price: 149,
		weight: 100,
		category: 'Молочные продукты',
		group: 'Сыры',
		imgUrl: 'webp125/сыр росс_125.webp',
		bigImgUrl: 'awif245/сыр росс_245.awif',
	},
	{
		id: 15,
		name: 'Сыр Рокфор',
		price: 379,
		weight: 100,
		category: 'Молочные продукты',
		group: 'Сыры',
		imgUrl: 'webp125/сыр рокфор_125.webp',
		bigImgUrl: 'awif245/сыр рокфор_245.awif',
	},
	{
		id: 16,
		name: 'Голубика',
		price: 69,
		weight: 100,
		category: 'Ягоды',
		group: 'Ягоды',
		imgUrl: 'webp125/голубика_125.webp',
		bigImgUrl: 'awif245/голубика_245.awif',
	},
	{
		id: 17,
		name: 'Клубника',
		price: 79,
		weight: 100,
		category: 'Ягоды',
		group: 'Ягоды',
		imgUrl: 'webp125/клубника_125.webp',
		bigImgUrl: 'awif245/клубника_245.awif',
	},
	{
		id: 18,
		name: 'Малина',
		price: 89,
		weight: 100,
		category: 'Ягоды',
		group: 'Ягоды',
		imgUrl: 'webp125/малина_125.webp',
		bigImgUrl: 'awif245/малина_245.awif',
	},
];
